#!/usr/bin/env ruby

require "optparse"
require "uri"

require "nokogiri"

require "webg/version"

module Fetcher
end

class Fetcher::Raw
  def call(uri)
    require("open-uri")
    return uri.read
  end
end

class Fetcher::Firefox
  def call(uri)
    require("capybara")
    session = Capybara::Session.new(:selenium_headless)
    session.visit(uri)
    return session.body
  end
end

module Selector
end

class Selector::All
  REJECT_TAG_NAMES = %w[script noscript style]

  def raw(document)
    return document.to_s
  end

  def text(document)
    document.css(REJECT_TAG_NAMES.join(", ")).remove
    return document.inner_text
  end
end

class Selector::Css
  def initialize(css_selectors)
    @css_selectors = css_selectors
  end

  def raw(document)
    return nodes(session).map { |node|
      node.evaluate_script('this.outerHTML')
    }.join("\n")
  end

  def text(session)
    return nodes(session).map(&:text).join("\n")
  end

  private

  def nodes(session)
    return session.all(@css_selectors.join(", "))
  end
end

def parse_options(argv)
  argv = argv.dup
  fetcher = :raw
  css_selectors = []
  text = false

  parser = OptionParser.new
  parser.version = Webg::VERSION
  parser.banner = "Usage: #{File.basename(Process.argv0)} [options] uri"
  parser.separator("")
  parser.separator("Options:")
  parser.on(
    "--firefox",
    "use Firefox to fetch web page. slow, but JavaScript-evaluatable",
  ) do
    fetcher = :firefox
  end
  parser.on(
    "--css-selector=SELECTOR",
    "specify css selector to filter output.",
  ) do |selector|
    css_selectors << selector
  end
  parser.on(
    "--text",
    "output only text",
  ) do
    text = true
  end
  parser.parse!(argv)

  uri = argv.shift
  if !uri
    $stderr.puts(parser.help)
    exit(1)
  end
  uri = URI(uri)

  return uri, fetcher, css_selectors, text
end

begin
  uri, fetcher_name, css_selectors, text = parse_options(ARGV)

  fetcher = Fetcher.const_get(fetcher_name.capitalize).new
  selector = css_selectors.empty? ? Selector::All.new : Selector::Css.new(css_selectors)
  output_method_name = text ? :text : :raw

  document = Nokogiri::HTML.parse(fetcher.(uri))
  puts(selector.public_send(output_method_name, document))
rescue => e
  $stderr.puts(e.message)
  exit(1)
end
